### ISSUE TITLE
Original software licence of orthoMCL violated?

### ISSUE THREAD

**Issue by greatfireball** [etabari/PorthoMCL#1]
Dear Ehsan,

thanks for your work on PorthoMCL. It seems to be promising to enable faster determination of orthologs for huge data sets. I am no lawyer, but I think you have to change our licence to GPL3 due to the original orthoMCL files require that licence (http://www.orthomcl.org/common/downloads/software/v2.0/SoftwareLicense.txt). Otherwise you should re-implement the functionality of those scripts.

Thanks again!

Best regards,
Frank

**Comment by etabari** [comment]
Hi. Thanks for noticing that. I'll take care of it.

-Ehsan
