### ISSUE TITLE
Difference between original orthomcl and porthomcl

### ISSUE THREAD

**Issue by kevlim83** [etabari/PorthoMCL#2]
Hi,

I read your paper with great interest. Thanks for developing this tool. I also noticed some differences in methodology which perhaps you can help me understand further.

In the original orthomcl, protein pairs of 1) orthologs, 2) paralogs and 3) coorthologs were first derived and merged into a single large network before mcl is run.

However, I read in both your paper and the detailed manual and found that the slight difference is that you do not merge these pairs into one single network but run mcl on separate networks representing the orthologs and paralogs. I am curious to know if this might cause differences in final interpretation of results since the starting network is different? Also, it seems that you have not mentioned coorthologs in both the manuscript and the detailed manual even though you have a script for that. I am also curious to learn why.

It would be helpful if you can explain the rationale behind the choice of your methodology.

Thanks a bunch!

Regards,
K

**Comment by etabari** [comment]
I do not merge the results by default, yet the results of orthologs and paralogs can be concatenated before running MCL if you wish so. I developed PorthoMCL for a research in which I need the ortholog groups rather than all the genes that have evolutionary background. For the same reason, coorthologs were not implemented in this implementation.

**Comment by kevlim83** [comment]
Hi,

Can I check if you might be still developing the coortholog idea further? I think it has great potential for users who might not want to use mysql database for the original orthomcl.

Thanks.
